name: my_town
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dapackages: ^1.1.1

  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.14
  firebase_storage: ^3.1.6
  firebase_messaging: ^6.0.16

  geoflutterfire: ^2.1.0

  cloud_firestore: ^0.13.6

  firebase_auth: ^0.16.1
  firebase_auth_web: ^0.1.3+1

  google_sign_in: ^4.5.1
  flutter_auth_buttons: ^0.8.0

  rxdart: ^0.23.1
  provider: ^4.1.3

  camera: ^0.5.8+2
  image_picker: ^0.6.7+1
  cached_network_image: ^2.2.0+1

  flutter_bloc: ^4.0.0  # bloc pattern widgets
  bloc: ^4.0.0 # bloc pattern
  equatable: ^1.2.0
  network_image_to_byte: ^0.0.1

  http: ^0.12.1

  responsive_scaffold: ^1.3.0+2

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  i18n_extension: ^1.4.0
  
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/anonymous_avatar.png
   - assets/badges/reporter.png
